### ISSUE TITLE
Feature #1: User can pick a randomized Tarot Card

### ISSUE THREAD

**Issue by msandersmontandon** [msandersmontandon/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can pick a randomized Tarot Card

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once selecting the "Pick a Card" option (by clicking the button of the same name), a new card will appear centered in the body area. The card will be one from the 78 tarot cards from the Rider-Waite-Smith deck.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-19 at 12 35 15 PM](https://user-images.githubusercontent.com/78445066/164083402-39691ab4-7f9b-45c7-9037-d906e6de00b4.png)
![Screen Shot 2022-04-19 at 12 35 26 PM](https://user-images.githubusercontent.com/78445066/164083432-4ee8be10-b038-4e26-b4f2-8e100e12bc3d.png)
![Screen Shot 2022-04-19 at 12 35 48 PM](https://user-images.githubusercontent.com/78445066/164083455-f7d0ba7b-d93b-4473-bb9e-1f2f130d2ac7.png)
![Screen Shot 2022-04-19 at 12 35 56 PM](https://user-images.githubusercontent.com/78445066/164083468-6f4c9ac8-810d-4d1d-9735-146d7c28cf18.png)
![Screen Shot 2022-04-19 at 12 36 11 PM](https://user-images.githubusercontent.com/78445066/164083494-7f8e5458-82ee-44a7-a107-fecdd293a7d6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Create the following documents: index.html, styles.css, data.js & main.js
- [x] Make the html skelleton
- [x] Link the styles.css and the data.js in the head element, and link the main.js at the bottom of the body element
- [x] make a header element
- [x] make the html of the header, including a "Pick a Card" buttom and a selection Icon for the mobile layout
- [x] make the layout classes on css, including a .hidden rule set
- [x] finish the css for the header, including for the mobile cases
- [x] make a main element
- [x] make the background for the main element, including the background picture
- [x] make the css for the main element and background
- [x] make a card display element on the main element, and give it a dummy source
- [x] style the card display element
- [x] hidde the card display 
- [x] make the DOM objects for the header element, and for the main element
- [x] make a function for picking a random card (use ajax for it)
- [x] make an event listener for calling the card-picking function when the Pick a Card buttom is clicked
- [x] ...
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
