### ISSUE TITLE
Feature #2: User can see the meaning of selected card

### ISSUE THREAD

**Issue by msandersmontandon** [msandersmontandon/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the meaning of selected card

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking on the card will open a modal with the card in highlight, and a text box with the description for said card

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-19 at 1 25 50 PM](https://user-images.githubusercontent.com/78445066/164089994-363c9317-7ae5-40fe-a508-ead908b9b298.png)
![Screen Shot 2022-04-19 at 1 25 59 PM](https://user-images.githubusercontent.com/78445066/164090008-ef441cf7-8f46-48fe-9e39-f5679028ac7b.png)
![Screen Shot 2022-04-19 at 1 26 17 PM](https://user-images.githubusercontent.com/78445066/164090024-e9cfd9cc-5ae4-4b0d-8a9e-eb7a96932261.png)
![Screen Shot 2022-04-19 at 1 26 53 PM](https://user-images.githubusercontent.com/78445066/164090045-ded6ea3b-978f-4a8d-86ed-6eb3de556143.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Make the html for the foreground modal, including for the card element and the text box.
- [x] Have a dummy value for the html, and stylize the elements in css.
- [x] create an event listener for when a card is clicked
- [x] create an event handler function to showecase the foreground modal with the card
- [x] create an event listener for when the modal card gets clicked
- [x] create an event handler function to showcase the text description for the card
- [x] if the foreground modal is clicked (besides the card and the text box), reset the foreground modal's elements' values and hide the foreground modal
- [x] ...
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
