### ISSUE TITLE
Feature #3: User can search for an specific card

### ISSUE THREAD

**Issue by msandersmontandon** [msandersmontandon/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for an specific card

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A searchbox is now implemented, and with it the user can find specific cards

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-19 at 2 35 57 PM](https://user-images.githubusercontent.com/78445066/164105960-23dd4a45-e324-4137-8dfc-4c4dd26e26bc.png)
![Screen Shot 2022-04-19 at 2 36 07 PM](https://user-images.githubusercontent.com/78445066/164105973-d2545ac9-2177-45ad-89c2-bb84cfc59807.png)
![Screen Shot 2022-04-19 at 2 36 17 PM](https://user-images.githubusercontent.com/78445066/164105992-d95e7b66-e190-438c-9f54-e2c002cd4995.png)
![Screen Shot 2022-04-19 at 2 36 27 PM](https://user-images.githubusercontent.com/78445066/164106007-b72082ed-1f01-4c19-bfe5-da7e8e022d58.png)
![Screen Shot 2022-04-19 at 2 35 41 PM](https://user-images.githubusercontent.com/78445066/164106020-abf4c57a-a76a-4ae3-af4f-c422ab7f561b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Make the html search form and button, for both mobile and desktop
- [x] Make the css for the new features, both mobile and desktop
- [x] Make a DOM object for the forms, both mobile and desktop
- [x] Have the mobile form hidden, unless and until the menu button is clicked
- [x] Make the event listener for the form submission
- [x] Make the event handler function for sending a GET request to search a card by the content of the search form
- [x] ...
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
