### ISSUE TITLE
Feature #4: User can make a simple, three card spread

### ISSUE THREAD

**Issue by msandersmontandon** [msandersmontandon/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can make a simple, three card spread

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking on the "Make a Spread" button picks three randomized cards and spread them to be viewed by the user

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-19 at 2 39 39 PM](https://user-images.githubusercontent.com/78445066/164106940-5017ecfc-538a-454e-adf8-4fd5f3205020.png)
![Screen Shot 2022-04-19 at 2 39 52 PM](https://user-images.githubusercontent.com/78445066/164106949-30ff7b14-4afe-4a74-ad87-a696e33b129b.png)
![Screen Shot 2022-04-19 at 2 40 03 PM](https://user-images.githubusercontent.com/78445066/164106960-1f0a3381-833a-4230-882f-6251b8863c79.png)
![Screen Shot 2022-04-19 at 2 40 13 PM](https://user-images.githubusercontent.com/78445066/164106978-ea016084-d0a4-4461-ba6b-bf02bc4b6570.png)
![Screen Shot 2022-04-19 at 2 41 17 PM](https://user-images.githubusercontent.com/78445066/164106987-7033b635-2929-42a0-a867-18d71bf2c51f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] make the html for the spread buttons, both the mobile and the desktop version,
- [x] make the css for the spread elements, both the mobile and the desktop version,
- [x] make the DOM object for the spread buttons, both the mobile and the desktop version,
- [x] make an event listener for when the spread buttons are clicked,
- [x] make an event handler that'll deal three cards
- [x] ...
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
