### ISSUE TITLE
Feature #5: User can log and access their spread

### ISSUE THREAD

**Issue by msandersmontandon** [msandersmontandon/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user can now log and access past spreads

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can log their spread with the plus button, name said spread, and access old logs in the "My Spreads" section

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-19 at 3 35 08 PM](https://user-images.githubusercontent.com/78445066/164120648-98c6795d-34b2-4498-85a7-7b452365e677.png)
![Screen Shot 2022-04-19 at 5 49 49 PM](https://user-images.githubusercontent.com/78445066/164125604-a1ac8399-bb1e-4622-9025-414dc2a527a1.png)
![Screen Shot 2022-04-19 at 5 50 00 PM](https://user-images.githubusercontent.com/78445066/164125617-efcd5f30-eaeb-4bee-88d9-4e9b8562bcdf.png)
![Screen Shot 2022-04-19 at 5 50 11 PM](https://user-images.githubusercontent.com/78445066/164125625-cab3c9a0-1a1f-4631-836f-56f75f9edd93.png)
![Screen Shot 2022-04-19 at 5 54 41 PM](https://user-images.githubusercontent.com/78445066/164125638-83a424ad-463c-439a-a8b6-6e742f721c1d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Make the html for the my spread button, the add button, the save form, the save button and the cancel button, both for mobile and desktop versions.
- [ ] Make the css for the new elements, including both mobile and desktop versions.
- [ ] Make the DOM object for the my spread buttons, both mobile and desktop versions.
- [ ] Add an event listener for when the my spread buttons are clicked.
- [ ] Make an event handler function for opening up the header section with the saved spreads options, as well as the add button.
- [ ] Make the DOM object for the add button, including both the mobile and desktop versions.
- [ ] Add an event listener for when the add button is clicked.
- [ ] Make the event handler function for opening up the save form for the button, as well as calling the curtain.
- [ ] Make the DOM object for the save form, including both the mobile and desktop versions.
- [ ] Add an event listener for when the save form is submitted.
- [ ] Make the event handler for saving the current spread to the data and adding a new button for accessing it, as well as for getting rid of the curtain.
- [ ] Make the DOM object for the cancel button, including both the mobile and desktop versions.
- [ ] Add an event listener for when the cancel button is clicked.
- [ ] Make the event handler for exiting the save a spread otipon.
- [ ] Add an event listener for when the page is about to unload.
- [ ] Make the event handler to update the data object and store it locally.
- [ ] Make the first piece of code to run a function call to load the data from local storage and then update any saved spreads from it.
- [ ] ...
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
